version: "3.9"

services:
  app:
    build: .
    container_name: psychic_journey
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
